- operation: Add
  participant_description:
    name: box_bot_1
    group: box_bot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.10000000000000001
        - 0.12
- operation: Add
  participant_description:
    name: box_bot_2
    group: box_bot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.10000000000000001
        - 0.12
- operation: Add
  participant_description:
    name: box_bot_3
    group: box_bot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.10000000000000001
        - 0.12